type: object
x-stoplight:
  id: 7cg7vdi23zi97
description: 'Application id and name registered within the SE Asset Management system. If the application is both an API consumer and a proxy provider, it shares one of these records.'
required:
  - assetId
  - assetName
properties:
  assetId:
    type: string
    x-stoplight:
      id: u92gm2gjzynat
    description: Unique asset id for this application
    example: '50600'
  assetName:
    type: string
    x-stoplight:
      id: jgfpvau3zeu6c
    description: Application asset name
    example: SE API Management
title: Application Asset
