type: object
x-stoplight:
  id: r3qotoue7cxur
description: 'Relationship between a product and a proxy for a specific SEAPIM org, including the date this relationship become live or was decommissioned/removed from Seapim.'
required:
  - seapimOrg
  - createdAt
  - updatedAt
  - product
  - proxy
properties:
  seapimOrg:
    $ref: ./SEAPIM Org.yaml
    x-stoplight:
      id: h13grqog03wz0
    description: SEAPIM organisation where the resources exist
  wentLiveOn:
    type: string
    format: date-time
    x-stoplight:
      id: ac1ojnp0moc0c
    example: '2025-08-11T05:49:57.000Z'
    description: Date the product proxy relationship went live
  decommissionedOn:
    type: string
    format: date-time
    x-stoplight:
      id: d38t2adbqtlmh
    example: '2025-12-11T05:49:57.000Z'
    description: Date the product proxy relationship was decommissioned
  createdAt:
    $ref: ../models/CreatedAt.yaml
    description: The time this record was created
    x-stoplight:
      id: c2baqcvlhzb1p
  updatedAt:
    $ref: ../models/UpdatedAt.yaml
    description: The time this record was last updated
    x-stoplight:
      id: x4eekba0o3z53
  product:
    $ref: ./Product.yaml
    x-stoplight:
      id: lgwvpfvnncs5v
    description: Product
  proxy:
    $ref: ./Proxy.yaml
    x-stoplight:
      id: dlv29hlxrlwcu
    description: API Proxy
title: Product Proxy
