type: object
x-stoplight:
  id: myj9qlkqutdw7
description: |-
  Seapim product that groups one or more API proxies.

  A record is uniquely identified by seapimOrg + productName combined
required:
  - id
  - seapimOrg
  - productName
  - createdAt
  - updatedAt
  - consumers
  - productProxies
properties:
  id:
    $ref: ../models/Id.yaml
    x-stoplight:
      id: vwt02nhuzu2gw
    description: Database identifier
  seapimOrg:
    $ref: ./SEAPIM Org.yaml
    x-stoplight:
      id: g2j2lot3g0ap5
    description: SEAPIM platform organisation name
  productName:
    type: string
    x-stoplight:
      id: r75h7ijusjl2r
    example: Product-SE API Managment
    description: Product name
  callRate:
    type: integer
    x-stoplight:
      id: 4ef8472hx5yai
    description: 'Allocated maximum number of API calls allowed per minute, converted from actual SEAPIM quota configuation which may be defined using a different time unit'
    example: 600
  quota:
    type: integer
    x-stoplight:
      id: 0u6k2ypnbka71
    description: 'SEAPIM quota number, first part of a triplet: quota number per (interval * time unit). For example 1000 per 2 * hour'
    example: 1000
  quotaInterval:
    type: integer
    x-stoplight:
      id: dj2um0bj1i3pr
    description: 'SEAPIM quota interval, second part of a triplet: quota number per (interval * time unit). For example 1000 per 2 * hour'
    example: 2
  quotaTimeunit:
    $ref: ./Quota Time Unit.yaml
    x-stoplight:
      id: bmeqx11bcmo25
    description: 'SEAPIM quota time unit, third part of a triplet: quota number per (interval * time unit). For example 1000 per 2 * hour'
  scopes:
    type: array
    x-stoplight:
      id: 7uoqni33vktoq
    description: 'List of API scopes which grant conditional access to specified API, using partial matching of operations by a string in the endpoint path'
    items:
      x-stoplight:
        id: q1piqsim5rss0
      type: string
      example: 'urn:API-Metadata-V2:*:read, urn:API-Metadata-V2:apis:write"'
  createdAt:
    $ref: ../models/CreatedAt.yaml
    description: The time this record was created
    x-stoplight:
      id: 1aixk5pjyha0m
  updatedAt:
    $ref: ../models/UpdatedAt.yaml
    description: The time this record was last updated
    x-stoplight:
      id: qy5kiwv2k41ra
  consumers:
    type: array
    x-stoplight:
      id: 6gpiirucvyj24
    description: List of application consumers with a subscription that refers to this product
    items:
      $ref: ./Consumer.yaml
      x-stoplight:
        id: 3gipvh2dynxbx
  productProxies:
    type: array
    x-stoplight:
      id: id17dzfv0zxyg
    description: List of API proxies included in this product
    items:
      $ref: ./Product Proxy.yaml
      x-stoplight:
        id: 6gamx543t7hzz
title: ''
