type: object
x-stoplight:
  id: 9m68lrpe6n48b
description: 'Application id and name registered within the SE Asset Management system. If the application is both an API consumer and a proxy provider, it shares one of these records.'
required:
  - assetId
  - assetName
properties:
  assetId:
    type: string
    x-stoplight:
      id: yhoytbf03hroj
    description: Unique asset id for this application
    example: '50600'
  assetName:
    type: string
    x-stoplight:
      id: nkdexok5l3ss1
    description: Application asset name
    example: SE API Management
title: Application Asset
