type: object
x-stoplight:
  id: a04dq6by5a4ji
title: Environment
description: 'Relationship between one set of requirements, and one specific SEAPIM deployment environment, CORS domain configuration, providers and consumers.'
required:
  - id
  - environment
  - createdAt
  - updatedAt
  - environmentDomains
  - environmentProviders
properties:
  id:
    $ref: ../models/Id.yaml
    x-stoplight:
      id: i75qy53pg3vi5
    description: Database identifier
  environment:
    $ref: ./SEAPIM Environment.yaml
    x-stoplight:
      id: rwyqshm1d4w51
    description: A SEAPIM deployment environment
  createdAt:
    $ref: ../models/CreatedAt.yaml
    description: The time this record was created
    x-stoplight:
      id: r1h3cdkdwwsxw
  updatedAt:
    $ref: ../models/UpdatedAt.yaml
    description: The time this record was last updated
    x-stoplight:
      id: oysh9d6p0c1eg
  environmentDomains:
    type: array
    x-stoplight:
      id: x0ossydn1p6av
    description: List of application domains used for CORS configuration
    items:
      $ref: ./Environment Domain.yaml
      x-stoplight:
        id: iwd96kub5yaxo
  environmentProviders:
    type: array
    x-stoplight:
      id: kwnlsxyp1rp9o
    description: Environment-specific list of API provider applications (backends)
    items:
      $ref: ./Environment Provider.yaml
      x-stoplight:
        id: 76do6pe37dimw
