type: object
x-stoplight:
  id: j4u0qxqugcdst
title: Environment Provider
description: |-
  An API provider application for a specific environment.

  A provider is also known as a backend application, a system that hosts the API service, lying behind the SEAPIM platform.
required:
  - assetId
  - createdAt
  - updatedAt
  - environment
properties:
  assetId:
    type: string
    x-stoplight:
      id: jt9og5oiwv1lo
    example: '12345'
    description: 'Application asset id, as defined in the SE asset management system'
  providerUrls:
    type: array
    x-stoplight:
      id: y53l2iide1u0a
    description: Provider system URL for this API
    items:
      x-stoplight:
        id: ffmgieb66h5n2
      type: string
      format: uri
  reverseProxies:
    type: array
    x-stoplight:
      id: mz3kl4i71qau5
    description: 'Regional reverse proxy details, if the provided is hosted in the SE private network'
    items:
      x-stoplight:
        id: giwga11cwifz7
      type: string
  instructions:
    type: string
    x-stoplight:
      id: 9ccgsmw2ybm5u
    description: Extra information to help connect with a provider
  createdAt:
    $ref: ../models/CreatedAt.yaml
    description: The time this record was created
    x-stoplight:
      id: 7luhab4yytipf
  updatedAt:
    $ref: ../models/UpdatedAt.yaml
    description: The time this record was last updated
    x-stoplight:
      id: skjy0vl56uria
  environment:
    $ref: ./Environment.yaml
    x-stoplight:
      id: fpw0yg1fboz4t
    description: API requirements-related SEAPIM environment
