type: object
x-stoplight:
  id: nh5qu1klo2xd1
description: |-
  Seapim product that groups one or more API proxies.

  A record is uniquely identified by seapimOrg + productName combined
required:
  - id
  - seapimOrg
  - productName
  - createdAt
  - updatedAt
  - consumers
  - productProxies
properties:
  id:
    $ref: ../models/Id.yaml
    x-stoplight:
      id: 5wy5ksdks56yx
    description: Database identifier
  seapimOrg:
    $ref: ./SEAPIM Org.yaml
    x-stoplight:
      id: rmp8hqplga5kr
    description: SEAPIM platform organisation name
  productName:
    type: string
    x-stoplight:
      id: xdt7zu6sxys6g
    example: Product-SE API Managment
    description: Product name
  callRate:
    type: integer
    x-stoplight:
      id: 4us9bn147worp
    description: 'Allocated maximum number of API calls allowed per minute, converted from actual SEAPIM quota configuation which may be defined using a different time unit'
    example: 600
  quota:
    type: integer
    x-stoplight:
      id: bqolhx1du0twk
    description: 'SEAPIM quota number, first part of a triplet: quota number per (interval * time unit). For example 1000 per 2 * hour'
    example: 1000
  quotaInterval:
    type: integer
    x-stoplight:
      id: 0yr7cemwd8lx1
    description: 'SEAPIM quota interval, second part of a triplet: quota number per (interval * time unit). For example 1000 per 2 * hour'
    example: 2
  quotaTimeunit:
    $ref: ./Quota Time Unit.yaml
    x-stoplight:
      id: 6mm5vbqdelnye
    description: 'SEAPIM quota time unit, third part of a triplet: quota number per (interval * time unit). For example 1000 per 2 * hour'
  scopes:
    type: array
    x-stoplight:
      id: k38la3zb1vkkj
    description: 'List of API scopes which grant conditional access to specified API, using partial matching of operations by a string in the endpoint path'
    items:
      x-stoplight:
        id: tvu2mplq18zmv
      type: string
      example: 'urn:API-Metadata-V2:*:read, urn:API-Metadata-V2:apis:write"'
  createdAt:
    $ref: ../models/CreatedAt.yaml
    description: The time this record was created
    x-stoplight:
      id: 6fspfvwrfjrxs
  updatedAt:
    $ref: ../models/UpdatedAt.yaml
    description: The time this record was last updated
    x-stoplight:
      id: idd20u4hddvv8
  consumers:
    type: array
    x-stoplight:
      id: 15ml8vpl8cfw7
    description: List of application consumers with a subscription that refers to this product
    items:
      $ref: ./Consumer.yaml
      x-stoplight:
        id: ns0uua62wikjj
  productProxies:
    type: array
    x-stoplight:
      id: 3z873bezfc691
    description: List of API proxies included in this product
    items:
      $ref: ./Product Proxy.yaml
      x-stoplight:
        id: 37ahpv7zdbbp0
title: Product
