type: object
x-stoplight:
  id: hbf73oq8mz9jo
description: 'Application id and name registered within the SE Asset Management system. If the application is both an API consumer and a proxy provider, it shares one of these records.'
required:
  - assetId
  - assetName
properties:
  assetId:
    type: string
    x-stoplight:
      id: il3bki7yjnfg2
    description: Unique asset id for this application
    example: '50600'
  assetName:
    type: string
    x-stoplight:
      id: 992jmllc33ewn
    description: Application asset name
    example: SE API Management
title: Application Asset
