type: object
x-stoplight:
  id: 858lelk5zncxe
title: Environment Domain
description: This captures the list of CORS domains that need to be whitelisted for a given API proxy. Specifically thevalues that would go in the Access Control Allow Origin header.
required:
  - createdAt
  - updatedAt
properties:
  domains:
    type: array
    x-stoplight:
      id: xebq7hb5irhof
    description: List of domains that are to be whitelisted
    items:
      x-stoplight:
        id: fh4uz3d6br9vl
      type: string
  createdAt:
    $ref: ../models/CreatedAt.yaml
    description: The time this record was created
    x-stoplight:
      id: 0exn26nxrue4l
  updatedAt:
    $ref: ../models/UpdatedAt.yaml
    description: The time this record was last updated
    x-stoplight:
      id: qalmz878mtcw0
