type: object
x-stoplight:
  id: pj689ylu9923v
description: 'Relationship between a product and a proxy for a specific SEAPIM org, including the date this relationship become live or was decommissioned/removed from Seapim.'
required:
  - seapimOrg
  - createdAt
  - updatedAt
  - product
  - proxy
properties:
  seapimOrg:
    $ref: ./SEAPIMOrg.yaml
    x-stoplight:
      id: v8hw48i52ez6h
    description: SEAPIM organisation where the resources exist
  wentLiveOn:
    type: string
    format: date-time
    x-stoplight:
      id: 9c5hw97l1rd1p
    example: '2025-08-11T05:49:57.000Z'
    description: Date the product proxy relationship went live
  decommissionedOn:
    type: string
    format: date-time
    x-stoplight:
      id: w64c2tp1wbo5q
    example: '2025-12-11T05:49:57.000Z'
    description: Date the product proxy relationship was decommissioned
  createdAt:
    $ref: ../models/CreatedAt.yaml
    description: The time this record was created
    x-stoplight:
      id: 01elbvch87yl0
  updatedAt:
    $ref: ../models/UpdatedAt.yaml
    description: The time this record was last updated
    x-stoplight:
      id: ub128onpnwzcy
  product:
    $ref: ./Product.yaml
    x-stoplight:
      id: lozavopgdwudv
    description: Product
  proxy:
    $ref: ./Proxy.yaml
    x-stoplight:
      id: mfo4gcrwl1p70
    description: API Proxy
title: Product Proxy
