type: object
x-stoplight:
  id: oui3tnznsnt8l
description: |-
  Seapim product that groups one or more API proxies.

  A record is uniquely identified by seapimOrg + productName combined
required:
  - id
  - seapimOrg
  - productName
  - createdAt
  - updatedAt
  - consumers
  - productProxies
properties:
  id:
    $ref: ../models/Id.yaml
    x-stoplight:
      id: yv56b3tg7am7z
    description: Database identifier
  seapimOrg:
    $ref: ./SEAPIMOrg.yaml
    x-stoplight:
      id: ourewccfx81p8
    description: SEAPIM platform organisation name
  productName:
    type: string
    x-stoplight:
      id: k40pf1kz8dfrc
    example: Product-SE API Managment
    description: Product name
  callRate:
    type: integer
    x-stoplight:
      id: ekap5ytxhzp9q
    description: 'Allocated maximum number of API calls allowed per minute, converted from actual SEAPIM quota configuation which may be defined using a different time unit'
    example: 600
  quota:
    type: integer
    x-stoplight:
      id: gh5rg4cbwuevu
    description: 'SEAPIM quota number, first part of a triplet: quota number per (interval * time unit). For example 1000 per 2 * hour'
    example: 1000
  quotaInterval:
    type: integer
    x-stoplight:
      id: ce2izy9qwgljo
    description: 'SEAPIM quota interval, second part of a triplet: quota number per (interval * time unit). For example 1000 per 2 * hour'
    example: 2
  quotaTimeunit:
    $ref: ./Quota_timeunit.yaml
    x-stoplight:
      id: 0h7by6oon5va3
    description: 'SEAPIM quota time unit, third part of a triplet: quota number per (interval * time unit). For example 1000 per 2 * hour'
  scopes:
    type: array
    x-stoplight:
      id: tww8w8ujdy9d3
    description: 'List of API scopes which grant conditional access to specified API, using partial matching of operations by a string in the endpoint path'
    items:
      x-stoplight:
        id: aeac3uynloic2
      type: string
      example: 'urn:API-Metadata-V2:*:read, urn:API-Metadata-V2:apis:write"'
  createdAt:
    $ref: ../models/CreatedAt.yaml
    description: The time this record was created
    x-stoplight:
      id: 3hrxbrb3x9d8c
  updatedAt:
    $ref: ../models/UpdatedAt.yaml
    description: The time this record was last updated
    x-stoplight:
      id: 2olc265znzj7m
  consumers:
    type: array
    x-stoplight:
      id: 6kxe1bgwd96eq
    description: List of application consumers with a subscription that refers to this product
    items:
      $ref: ./Consumer.yaml
      x-stoplight:
        id: k9k58tp2gtzuz
  productProxies:
    type: array
    x-stoplight:
      id: o4l8cnsgh0xxf
    description: List of API proxies included in this product
    items:
      $ref: ./ProductProxy.yaml
      x-stoplight:
        id: e4y17mizg09h3
title: ''
